<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-04-02 06:09
=======
# Generated by Django 3.0.2 on 2020-03-29 16:15
>>>>>>> 0dd0e3b21922737513deef862237cc0fd192f1ec

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
<<<<<<< HEAD
=======
                ('jdate', models.CharField(max_length=100)),
>>>>>>> 0dd0e3b21922737513deef862237cc0fd192f1ec
                ('email', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='feedbackreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('stdid', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('ques1', models.CharField(max_length=100)),
                ('ques2', models.CharField(max_length=100)),
                ('ques3', models.CharField(max_length=100)),
                ('ques4', models.CharField(max_length=100)),
                ('ques5', models.CharField(max_length=100)),
                ('overall', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='books/pdf/')),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 0dd0e3b21922737513deef862237cc0fd192f1ec
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='startfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='stdprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('branch', models.CharField(max_length=100)),
=======
>>>>>>> 0dd0e3b21922737513deef862237cc0fd192f1ec
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='subjectallotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
