# Generated by Django 3.0.2 on 2020-03-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='books/pdf/')),
            ],
        ),
    ]
