# Generated by Django 3.0.2 on 2020-04-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_subject_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facprofile',
            name='jdate',
        ),
    ]
